### ISSUE TITLE
Error that is resolved by clearing browser cache

### ISSUE THREAD

**Issue by Arnei** [opencast/opencast-admin-interface#231]
Some users have been getting a completely broken ui and an error in the console logs like `RangeError: Format string contains an unescaped latin alphabet character `n``.

I'm not sure, but this is likely cause by redux persist. If users persist and old redux state in their browser, and then open a newer version where there have been changes to the redux state structure, this may cause issues. This requires futher testing though.

If it truly is a problem with redux persist, I wouldn't mind removing it, since I'm not exactly sure what we're hoping to achieve by using it anyway.

**Comment by KatrinIhler** [comment]
![Screenshot from 2023-11-24 12-09-21](https://github.com/opencast/opencast-admin-interface/assets/11960278/b7de67b6-fafb-4d1b-8e8c-cb20442eeaad)

Screenshot of the mentioned error.
