### ISSUE TITLE
Scheduling is broken

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast-admin-interface#234]
Tested with 15.0:

- Go to capture-admin REST docs
- Register a capture agent and set it to `idle`
- Go to admin interface
- Open “Add Event” dialog
- Select “Schedule a single event”
- The entire UI breaks (blank page)

Demo:

https://github.com/opencast/opencast-admin-interface/assets/1008395/72bd89de-0c3f-4eaa-8d83-650557b99c85

**Comment by Arnei** [comment]
That'll be fixed by #205

**Comment by Arnei** [comment]
Was fixed by #205
