### ISSUE TITLE
Publication link not clickable

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast-admin-interface#238]
Sometimes, the publication dialog closes before you can click the link for the player, making it impossible to watch the video.
This doesn't appear to happen every time, but I have seen it several times now.

https://github.com/opencast/opencast-admin-interface/assets/1008395/10844237-2292-48e8-8bf3-3dc8d22b8026

**Comment by Arnei** [comment]
Will probably be fixed by #217

**Comment by Arnei** [comment]
Resolved by #217
