### ISSUE TITLE
Missing Translation Strings

### ISSUE THREAD

**Issue by gregorydlogan** [opencast/opencast-admin-interface#260]
Per Matrix discussion on 24-01-08, the translation strings need to be updated because there are new keys in the upstream crrowdin repo that are not present in the copy here.  This doesn't outright crash anything, but it does print the raw translation key, leading to stuff like this:
![image](https://github.com/opencast/opencast-admin-interface/assets/5639561/af2e9514-0851-4ed0-b1d6-7a099f01388a).

I would suggest automatically pulling in the translations from opencast/opencast via GHA rather than continuing to do this manually.  Modifying something like https://github.com/opencast/opencast/blob/develop/.github/workflows/update-translations.yml to clone the upstream (or just fetch it raw from GH), copy the relevant file(s), the commit and push here.

**Comment by ziegenberg** [comment]
Fix via #381 and #405.
