### ISSUE TITLE
Get rid of create-react-app

### ISSUE THREAD

**Issue by Arnei** [opencast/opencast-admin-interface#273]
This project uses Create-React-App. Create-React-App has been in-officially deprecated for quite some time now (the last release was over two years ago and active development has ceased since then). This will eventually lead to this project running into dependency versioning issues.

In the interest of keeping this projects dependencies up-to-date, we should eventually get rid of CRA. This issue may serve as a discussion hub on how to best move forward.

**Comment by lkiesow** [comment]
This is done by now. Closing.
