### ISSUE TITLE
Admin interface displays ACL rules from different events

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast-admin-interface#334]
It seems like the new admin interface will sometimes show ACL rules from different events. This can easily lead to accidents where a user overwrites the ACL set with an incorrect set of rules.

https://github.com/opencast/opencast-admin-interface/assets/1008395/85b96839-29c6-4185-a899-fb15b2280df9

**Comment by dennis531** [comment]
This bug still exists.
