### ISSUE TITLE
Checkboxes in Workflow selection: cannot set default to false

### ISSUE THREAD

**Issue by marwyg** [opencast/opencast-admin-interface#344]
I am not 100% sure about that, but you cannot set the default of checkboxes to false currently, for both UIs (old admin UI and new UI) at the same time.

TL;DR
If you put a checkbox in your workflow configuration and want the default to be false/unchecked with <input value="false" ... >, react or something, sets it to true again in the workflow selection (Upload Video / Add Event).

Situation 1
Checkbox in Workflow configuration: <input value="false">
Old Admin-UI: checkbox is not checked
New Admin-UI: checkbox is checked (React seems to set the "checked" attribute automatically and the value="true" so it becomes -> "<input value="true" checked>")

Situation 2
Checkbox in Workflow configuration: <input value="false" checked>
Old Admin-UI: checkbox is checked
New Admin-UI: checkbox is not checked

Description:

Normally, when someone wants to set a checkbox to false (in the code) the input html element has value="false" and doesn't have the "checked" attribute on them. When you want to set it to true, you set the value="true" and add the "checked" attribute.

In the old admin-UI, it works this way. Now in the new admin-ui, it doesn't seem to work, because the code seems to use only the "value" attribute, but strange enough, the "checked" attribute has always to be present. If the "checked" attribute isn't present, the code seems to add it automatically and sets the value attribute also automatically to "true". You can add the "checked" attribute, and set the value="false".. then it works in the new admin-ui, the checkbox-default is false as expected. But if you set it this way, the checkbox in the old admin-ui is checked, because it ignores the value="false" and only seems to use the "checked" attribute to determine if the checkbox is checked.

**Comment by Arnei** [comment]
In your first sentence you say that this problem occurs in both the old and new admin ui, then later say it only occurs in the new admin ui? Which one is it?

Could you share the workflows you used to test this (or at least the configuration part), and which UI and Opencast version you tested them with?

**Comment by marwyg** [comment]
Yea, sorry for the confusion, I really tried my best to be very clear and failed in the very first sentence 😂
I meant, that you cannot set the default to false in both cases simultaneously. I look for the config and put it in here.

**Comment by marwyg** [comment]
I cannot recreate this bug, maybe I mixed something up. 
But I noticed the missing configuration panel in the fast workflow like described in https://github.com/opencast/opencast/issues/5482.
