### ISSUE TITLE
Collapse roles in user table

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast-admin-interface#351]
The roles column in the user table can get extremely long in a production system. The [episode ID based access control via roles](https://github.com/opencast/opencast/pull/5056) will turn this even more into a problem.

![Screenshot from 2024-05-06 20-35-18](https://github.com/opencast/opencast-admin-interface/assets/1008395/eefcd98d-e77d-424a-83b1-f4d58fc814a3)

While we can't really do much about custom roles like in this screenshot, we could esily do something about the new episode ID based roles and just show something like:

> ROLE_X, ROLE_Y and 12 events

**Comment by gregorydlogan** [comment]
I'm sure the follow-on request would be 'I want to see which 12 events in a modal', so keep that in mind ;)
