### ISSUE TITLE
Add event upload options broken

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast-admin-interface#354]
The upload options in the add event dialog are pretty broken

![Screenshot from 2024-05-07 13-24-25](https://github.com/opencast/opencast-admin-interface/assets/1008395/e65ba970-28cc-44f9-b128-661b12e532f9)

- [ ] There is no space between `Presenter` and `(`
- [ ] The `(track: "flavor/sub-flavor")` is super technical and probably confusing to a lot of users
- [x] The subtitle upload is missing a translation
- [ ] `Slides` and `Presentation` is both used. We should use only one term. Presentation is probably the better term

**Comment by ziegenberg** [comment]
"The subtitle upload is missing a translation" was fixed via #381

**Comment by Arnei** [comment]
The first two points were also fixed. #758 attempts to fix the last point.
