### ISSUE TITLE
Header looks strange

### ISSUE THREAD

**Issue by Melanie-Koller** [opencast/opencast-admin-interface#450]
The header looks strange, if i have videos on the list with a long title.

![Bildschirmfoto 2024-05-24 um 07 05 22](https://github.com/opencast/opencast-admin-interface/assets/57887263/6a70ec67-0d5d-48a6-a280-323af7273483)

**Comment by Melanie-Koller** [comment]
And also all series titles should be left aligned.

**Comment by gregorydlogan** [comment]
Trivial reproduction: I moved the admin ui to one side of my 2K display, and got this (note the start and stop date sorters):

![image](https://github.com/opencast/opencast-admin-interface/assets/5639561/a48358c3-44b2-420b-ac78-ed149139e9cc)
