### ISSUE TITLE
Save Filter Sets (German)

### ISSUE THREAD

**Issue by Melanie-Koller** [opencast/opencast-admin-interface#453]
The window “Save Filter Sets” in german: The “Speichern” button is too far down.

![09](https://github.com/opencast/opencast-admin-interface/assets/57887263/5c62e87e-0447-4c85-8c50-72bac7e86535)

That is not so important.

**Comment by Arnei** [comment]
This has been fixed in the meantime.
![Bildschirmfoto vom 2024-06-18 12-42-46](https://github.com/opencast/opencast-admin-interface/assets/14070005/1c73a7e9-e40e-46ee-b80b-e43dbdb81d42)
