### ISSUE TITLE
Date Filter

### ISSUE THREAD

**Issue by Melanie-Koller** [opencast/opencast-admin-interface#455]
The date filter is working. But if i choose the date filter in the list, there is only 1 event.

![Bildschirmfoto 2024-05-24 um 08 20 45](https://github.com/opencast/opencast-admin-interface/assets/57887263/0546a998-4217-45b9-9fd5-727734591f2e)

![Bildschirmfoto 2024-05-24 um 08 21 16](https://github.com/opencast/opencast-admin-interface/assets/57887263/de454909-65a0-4dfe-8b44-a6ed97e08158)

**Comment by Melanie-Koller** [comment]
If i choose the date filter with the calendar and select only one day, it is not working. It only works, if i write the date.

![Bildschirmfoto 2024-05-25 um 08 19 37](https://github.com/opencast/opencast-admin-interface/assets/57887263/6bb2e9cc-f074-4a14-9339-9c520ee08cee)

**Comment by Arnei** [comment]
This has since been fixed by the linked PRs I believe.
