### ISSUE TITLE
Title sorting descending

### ISSUE THREAD

**Issue by Melanie-Koller** [opencast/opencast-admin-interface#456]
The title sorting descending is not working properly.

![Bildschirmfoto 2024-05-24 um 08 54 13](https://github.com/opencast/opencast-admin-interface/assets/57887263/1c6da360-b365-40e9-a176-a4759238fa13)

**Comment by Arnei** [comment]
The issue here is that capitalized and non-capitalized titles are grouped, i.e. first all non-capitalized titles, then all capitalized titles. Iirc this is an old issue with how ElasticSearch in the backend handles sorting, anyone looking to fix this should check there first.

**Comment by mtneug** [comment]
This is probably related https://github.com/opencast/opencast/pull/5413.

**Comment by Arnei** [comment]
Closing this as a duplicate #853 (Yes, this was open first, I know)
