### ISSUE TITLE
Edit the metadata of multiple events

### ISSUE THREAD

**Issue by Melanie-Koller** [opencast/opencast-admin-interface#464]
If i like to change the date of multiple events with the same date, there is written "invalid date". And it is only possible to change the date with the calendar. I can't write the date.

![Bildschirmfoto 2024-05-25 um 08 33 39](https://github.com/opencast/opencast-admin-interface/assets/57887263/73d5039f-fc24-41e6-b5f5-b14e5a3407b4)

**Comment by Arnei** [comment]
#606 should make it so that "Invalid date" is not wrongly shown anymore.

On the most current version of the admin ui I am able to change the date both by calendar and by typing, so maybe that part of this issue was already fixed incidentally.
