### ISSUE TITLE
Video upload

### ISSUE THREAD

**Issue by Melanie-Koller** [opencast/opencast-admin-interface#465]
The part in brackets next to "Multipart: Presenter Part 1" should be removed.
In addition, the description should be in German everywhere.

![Bildschirmfoto 2024-05-23 um 16 05 00](https://github.com/opencast/opencast-admin-interface/assets/57887263/c783512a-cafd-4c87-80ba-96644512ae51)

It should look like this:

![Bildschirmfoto 2024-05-23 um 15 56 00](https://github.com/opencast/opencast-admin-interface/assets/57887263/ee71e796-c80c-4a3a-8142-fc9d88edbf0d)

**Comment by ziegenberg** [comment]
Fixed by #467
