### ISSUE TITLE
 Admin interface displays media preview from different events

### ISSUE THREAD

**Issue by Melanie-Koller** [opencast/opencast-admin-interface#466]
It is very good to have a preview in the media details:

![Bildschirmfoto 2024-05-25 um 09 33 08](https://github.com/opencast/opencast-admin-interface/assets/57887263/54cb1660-804d-4bdc-9112-c222d97bd461)

But if you look at the preview from another video, there is the preview from the last video:

![Bildschirmfoto 2024-05-25 um 09 33 42](https://github.com/opencast/opencast-admin-interface/assets/57887263/a13c51b9-312b-455c-8ace-063ed7476afd)

**Comment by lkiesow** [comment]
This is probably related to #334
