### ISSUE TITLE
Video upload - date and time

### ISSUE THREAD

**Issue by Melanie-Koller** [opencast/opencast-admin-interface#478]
If i upload a video there should be the actual date and time under "recording metadata - start date". This is only working if i refresh the page.

![Bildschirmfoto 2024-05-28 um 09 11 26](https://github.com/opencast/opencast-admin-interface/assets/57887263/526ec9a5-bab3-4128-94c4-5d6091340747)

I didn't notice that and uploaded a few videos. Now they have all the same time:

![Bildschirmfoto 2024-05-28 um 09 06 40](https://github.com/opencast/opencast-admin-interface/assets/57887263/44be1c86-6189-4865-b62d-4c71b297584e)

**Comment by lkiesow** [comment]
We think what's wrong is that we just set the time once instead of every time we open the dialog.
