### ISSUE TITLE
Event/Series Metadata

### ISSUE THREAD

**Issue by Melanie-Koller** [opencast/opencast-admin-interface#489]
In the event and series metadata window the "cancel" and "save" buttons are a little bit too far down.

![Bildschirmfoto 2024-05-28 um 13 07 13](https://github.com/opencast/opencast-admin-interface/assets/57887263/f2eb6ead-ab65-4b77-a5e1-16254dc4c21b)

![Bildschirmfoto 2024-05-28 um 13 07 48](https://github.com/opencast/opencast-admin-interface/assets/57887263/99c39b77-90de-4e4c-a5e5-4fd50e2091f1)

**Comment by marwyg** [comment]
https://github.com/opencast/opencast-admin-interface/pull/572 should fix the problem.
