### ISSUE TITLE
Fix dependency updattes

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast-admin-interface#510]
The following updates seem to have problems:

- [x] https://github.com/opencast/opencast-admin-interface/pull/443
- [x] https://github.com/opencast/opencast-admin-interface/pull/498
- [x] https://github.com/opencast/opencast-admin-interface/pull/499
- [x] https://github.com/opencast/opencast-admin-interface/pull/504

Take a look. Fix the problem.

**Comment by ziegenberg** [comment]
#504 was superseded by #514

**Comment by ziegenberg** [comment]
#498 was superseded by #512

**Comment by ziegenberg** [comment]
#499 was superseded by #513

**Comment by ziegenberg** [comment]
#442 was superseded by #511
