### ISSUE TITLE
Visual Alignment for New Theme Wizard Steps and Buttons

### ISSUE THREAD

**Issue by stefanosgeo** [opencast/opencast-admin-interface#516]
![Screenshot from 2024-06-04 08-51-43](https://github.com/opencast/opencast-admin-interface/assets/3663204/6db15399-5045-49e1-ab04-e14d712a21eb)
![Screenshot from 2024-06-04 08-40-31](https://github.com/opencast/opencast-admin-interface/assets/3663204/69c5a509-88c3-46ff-b65f-21ba7f196c9b)

**Comment by Arnei** [comment]
Partial duplicate of #485.
