### ISSUE TITLE
Filter per status in locations not working properly

### ISSUE THREAD

**Issue by stefanosgeo** [opencast/opencast-admin-interface#517]
![Screenshot from 2024-06-04 09-10-04](https://github.com/opencast/opencast-admin-interface/assets/3663204/729224c9-734c-47a6-92b6-132454d81537)
![Screenshot from 2024-06-04 09-09-47](https://github.com/opencast/opencast-admin-interface/assets/3663204/6534a7c0-11d6-4014-a3bc-447c5169c568)

**Comment by ziegenberg** [comment]
@stefanosgeo can we have a little bit more information on what exactly is not working and how you expect it to work?

**Comment by stefanosgeo** [comment]
@ziegenberg  yes sorry... It should display a message "no results found" or display the CAs with the filter status.  Here are two screenshots from my Opencast 14.x old Admin-UI

![Screenshot from 2024-06-04 10-37-44](https://github.com/opencast/opencast-admin-interface/assets/3663204/f4d31f7a-89aa-485b-aa5b-583dc0fb4ea4)
![Screenshot from 2024-06-04 10-37-19](https://github.com/opencast/opencast-admin-interface/assets/3663204/2ae28fe9-889f-4891-9809-6405e752383e)
