### ISSUE TITLE
Click on an entry in a cell makes OC crash

### ISSUE THREAD

**Issue by kaspot** [opencast/opencast-admin-interface#526]
No matter on what “link” you click in the table in the event overview: Peter Planner, Mock Series, etc. you get a blank screen and are not able to recover. You have to clear the cookies, to be able to reload the interface. 

![IMG_1478](https://github.com/opencast/opencast-admin-interface/assets/1519714/42ae8631-c006-4de4-9e50-42e8ca505d98)
![attatchment AbhcWK](https://github.com/opencast/opencast-admin-interface/assets/1519714/f1fafe40-718a-4fbb-a1dd-c177c6e44371)

**Comment by marwyg** [comment]
Not that anyone gets confused: #565 has nothing to do with this Issue here. I accidentally mentioned the wrong issue.

**Comment by dennis531** [comment]
I cannot reproduce this error. When I click on a link, the corresponding filter will be set. The edit table view works too. Could you check if the error still exists?
