### ISSUE TITLE
Comments styling issues

### ISSUE THREAD

**Issue by stefanosgeo** [opencast/opencast-admin-interface#527]
The submit button in the comments goes out of the modal body 

![Screenshot from 2024-06-04 11-02-55](https://github.com/opencast/opencast-admin-interface/assets/3663204/95c4974f-8a9f-4c16-921e-bbf99fdc6065)

Also the resolve checkbox in an existing comment is, IMO, too big in compare with the "resolve" text on the right 

![Screenshot from 2024-06-04 11-03-23](https://github.com/opencast/opencast-admin-interface/assets/3663204/543023fa-5d04-4809-af3f-c1be98c101a3)

**Comment by stefanosgeo** [comment]
I am not sure if this is the same css rule/class,  but the same happens if you try to change the location to a scheduled event in the scheduling tab.

![Screenshot from 2024-06-04 11-12-42](https://github.com/opencast/opencast-admin-interface/assets/3663204/d8a0bd60-f8d2-49db-aa3f-38a5949defb8)

**Comment by marwyg** [comment]
Related to https://github.com/opencast/opencast-admin-interface/issues/540
I created a PR for the first one: https://github.com/opencast/opencast-admin-interface/pull/565
And I am seeing now, that the CSS I removed in my PR messed up the 2nd page :P I will add more commits to https://github.com/opencast/opencast-admin-interface/pull/565 so it fixes the 2 first views you posted.

**Comment by marwyg** [comment]
Fix for the scheduling tab is out: https://github.com/opencast/opencast-admin-interface/pull/572
