### ISSUE TITLE
button styling and placement when changing startdate with date-/timepicker in event metadata is off

### ISSUE THREAD

**Issue by reiferschris** [opencast/opencast-admin-interface#531]
1. In event details (metadata tab) the button for the date/timepicker looks like a circle (When changing the starttime of an event)
the hover animation is also a circle
3. When changing the time a cancel and save button appear but are misaligned and put in the table

<img width="2153" alt="image" src="https://github.com/opencast/opencast-admin-interface/assets/34450887/50b35e46-8a38-494d-a32b-69afb597fa92">

**Comment by reiferschris** [comment]
Button placement is the same in this issue https://github.com/opencast/opencast-admin-interface/issues/527#issuecomment-2147020577

**Comment by marwyg** [comment]
https://github.com/opencast/opencast-admin-interface/pull/572 fixes this.
