### ISSUE TITLE
Edit multiple events of the same series are no more grouped by day of the week

### ISSUE THREAD

**Issue by stefanosgeo** [opencast/opencast-admin-interface#533]
In Opencast 14 editing multiple events form the same series (select x events from a specific series->actions->edit scheduled events)  would group the events by day of the week 
![Screenshot from 2024-06-04 11-18-28](https://github.com/opencast/opencast-admin-interface/assets/3663204/2fbb217c-d936-45f7-b779-cc3f6c94cebe)

This is not happening any more 
![Screenshot from 2024-06-04 11-18-45](https://github.com/opencast/opencast-admin-interface/assets/3663204/7e2ca31a-7ca9-4d3d-aeef-ba0e4254e2bc)

Bug or feature?

**Comment by reiferschris** [comment]
Definitively not feature ;) 
IMHO

**Comment by Arnei** [comment]
This was fixed, closing.
