### ISSUE TITLE
Filter field: Bug with filtering the table by Presenters 

### ISSUE THREAD

**Issue by kaspot** [opencast/opencast-admin-interface#538]
When you filter the table by presenter, by clicking on the presenters name, the table gets correctly filtered, but the filter filed (top right) doesn’t show the name. This is not consistent with the other filter options. When you fitler by an event name, it is shown in the filter filed (top right). 
![IMG_1482](https://github.com/opencast/opencast-admin-interface/assets/1519714/5434b7df-0143-4016-83be-7d493e4741e5)

![IMG_1484](https://github.com/opencast/opencast-admin-interface/assets/1519714/9e8bbc69-4483-4ffa-8017-519d7246fa0f)

tested on: https://develop.opencast.org/admin-ui/index.html

**Comment by Arnei** [comment]
Iirc we also had this in the old admin ui and it was convoluted as heck, but I can't find the related issue anymore...
