### ISSUE TITLE
Misplaced submit button in Event Details -> Comments section

### ISSUE THREAD

**Issue by ferishili** [opencast/opencast-admin-interface#540]
The submit button is off!
Under Event -> Details -> Comments

![Screenshot 2024-06-04 at 11 33 40](https://github.com/opencast/opencast-admin-interface/assets/53179227/76ff982c-1901-4e9b-8141-4a6d3f88d7e4)

**Comment by marwyg** [comment]
PR #565 let it looks like this now:

![grafik](https://github.com/opencast/opencast-admin-interface/assets/5593139/8b7943f5-fc52-45d0-8a6f-ade836dd52b1)
