### ISSUE TITLE
Max entries per page resets on language switch

### ISSUE THREAD

**Issue by Bahamut-Chocobo** [opencast/opencast-admin-interface#544]
Changing the maximum entries per page\
- on the events page (`/#/events/events`) or
- on the series page (`/#/events/series`) \

to something else than `10` and your are going to switch language (i.e. to `100`) the max. entires per page are reset to `10`.

Expected to keep the value when switching languages in the UI.

**Comment by Arnei** [comment]
Likely related: https://github.com/opencast/opencast-admin-interface/issues/447
