### ISSUE TITLE
Creating long title makes UI hard to interact

### ISSUE THREAD

**Issue by DominikKidery** [opencast/opencast-admin-interface#549]
Requires long scrolling to the side when adding very long text, doesn't cut off and shows whole text

![Screenshot from 2024-06-04 12-03-08](https://github.com/opencast/opencast-admin-interface/assets/82276825/cbddbf71-dc31-4817-9899-461ddaa5f580)

**Comment by Arnei** [comment]
Oof. For completions sake, where exactly did you add the very long text to?

**Comment by DominikKidery** [comment]
I've added it in the title field, but it happens on every field where you can freely add text

**Comment by marwyg** [comment]
#626 should fix all the modal windows (and also limit the tables columns a little bit)
