### ISSUE TITLE
Startdate is not localized in the Editor

### ISSUE THREAD

**Issue by Shinymonk** [opencast/opencast-admin-interface#555]
![Editor_StartdateNotLocalized](https://github.com/opencast/opencast-admin-interface/assets/4223485/181479e0-9e55-458a-8d34-929e33466741)

**Comment by Arnei** [comment]
Thanks for reporting that. However, the Opencast Editor has its own repository (confusing, I know). Please report issue related to the editor over there: https://github.com/opencast/opencast-editor/issues
