### ISSUE TITLE
Waveform in the editor should be there "instantly"/precalculated, takes more time than patience

### ISSUE THREAD

**Issue by Shinymonk** [opencast/opencast-admin-interface#557]
![WaveformGenerationWhenOpeningEditor](https://github.com/opencast/opencast-admin-interface/assets/4223485/a0172558-a900-4b41-8b6d-f2a98e35130b)

**Comment by Arnei** [comment]
Thanks for reporting that. However, the Opencast Editor has its own repository (confusing, I know). Please report issues related to the editor over there: https://github.com/opencast/opencast-editor/issues
