### ISSUE TITLE
License field content displays inconsistently in editor vs metadata

### ISSUE THREAD

**Issue by Shinymonk** [opencast/opencast-admin-interface#559]
![MetadataShowsALLRIGHTS_WhileEditorFullText](https://github.com/opencast/opencast-admin-interface/assets/4223485/e361ec86-4b91-4a35-9ef7-e00f09efbc98)

![ALLRIGHTS_WithMetadata](https://github.com/opencast/opencast-admin-interface/assets/4223485/cfaee4e9-36ce-4bae-a1b7-a76299ee49a8)

**Comment by Shinymonk** [comment]
![Uploading ALLRIGHTS_WithMetadata.png…]()

**Comment by Arnei** [comment]
Thanks for reporting that. However, the Opencast Editor has its own repository (confusing, I know). Please report issues related to the editor over there: https://github.com/opencast/opencast-editor/issues

**Comment by Shinymonk** [comment]
I didn't close this one, because both are referenced, admin-ui and editor

**Comment by Arnei** [comment]
Ah, fair point, should've read more closely ^^'
