### ISSUE TITLE
Error when opening Statistics Page

### ISSUE THREAD

**Issue by ferishili** [opencast/opencast-admin-interface#566]
When navigating to Statistics the type error pops up, which interrupts the rendering of all pages and shows a blank white page! (it is no-go)

![Screenshot 2024-06-04 at 13 49 19](https://github.com/opencast/opencast-admin-interface/assets/53179227/1cf19c66-700f-4697-bf90-0b01af7079ab)

**Comment by ferishili** [comment]
@ziegenberg no it is not! #282 is on the event -> details section
This one is in action bar on the left!

![Screenshot 2024-06-04 at 14 19 39](https://github.com/opencast/opencast-admin-interface/assets/53179227/bbb333bf-3f3e-4b5a-b0b7-d07b65f085f2)

**Comment by ziegenberg** [comment]
@ferishili, you are right. My bad. 😔

**Comment by ferishili** [comment]
No problem at all 👍
