### ISSUE TITLE
Sort list in drop down fields

### ISSUE THREAD

**Issue by snoesberger** [opencast/opencast-admin-interface#567]
The list in drop down fields isn't sorted. Examples are the language or series selection when creating a new event. I would expect the list in the drop down to be sorted in ascending order.

![grafik](https://github.com/opencast/opencast-admin-interface/assets/103581881/e99a4073-662f-4638-8859-dd7bc9141e22)

**Comment by Arnei** [comment]
FYI for anyone tackling this: Some of the information in the dropdowns is provided by Opencast list providers (aka config files) which can allow custom ordering which we might want to respect. For example see https://github.com/opencast/opencast/blob/develop/etc/listproviders/licenses.properties
