### ISSUE TITLE
Misplaced buttons when adding ACLs in both Event and Series Details area

### ISSUE THREAD

**Issue by ferishili** [opencast/opencast-admin-interface#570]
In Event oder Series Details modal navigate to Access policy section and click the `+ New policy` button.
The rendered buttons set for save and cancel are well off the place!

![Screenshot 2024-06-04 at 14 36 19](https://github.com/opencast/opencast-admin-interface/assets/53179227/580a35a3-ae62-4421-ae06-26523b0041c6)

**Comment by marwyg** [comment]
There are several Tabs in the series and event dialogs where the save and cancel button are misplaced. I think I fixed them all with: https://github.com/opencast/opencast-admin-interface/pull/572
