### ISSUE TITLE
Filter and pagination do not work well together

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast-admin-interface#577]
- Open admin interface with > 20 events
- Select to display 10 events per page
- Go to page 3
- Search for existing event

Opencast should show one page with one event.

Opencast shows no events, claims to be on page 1, but actually still seems to use the offset from page 3.

Changing the filter, we should always just jump to page 1.

**Comment by ferishili** [comment]
See #211
And specially: https://github.com/opencast/opencast-admin-interface/issues/211#issuecomment-1788798999
