### ISSUE TITLE
Improve event detail assets view

### ISSUE THREAD

**Issue by viwiebe** [opencast/opencast-admin-interface#623]
![oseventdetails](https://github.com/opencast/opencast-admin-interface/assets/37619925/ef0246ba-f86e-4417-9335-d0dfa64f39b1)

When browsing the assets in the event details, you can click on the "details" link in the right column, after which the main asset (e.g. Attachments) becomes a tab link above the content and you can further click on more details, which only then appear as tabs:

![oc_assets](https://github.com/opencast/opencast-admin-interface/assets/37619925/5ce79705-2fca-45a0-a8ae-539c844ffed5)
![oc_assets2](https://github.com/opencast/opencast-admin-interface/assets/37619925/9714b64b-5197-4c17-ae62-df8b14b4e8bd)

Suggestion: make the top-level tabs available from the start so you can switch more easily between them and don't have to click on assets again first.

**Comment by dennis531** [comment]
[Screencast from 25.06.2024 13:20:27.webm](https://github.com/opencast/opencast-admin-interface/assets/44410838/abe7e8bd-425d-48df-ada5-972e8731e9d8)

How do you like this solution?
