### ISSUE TITLE
Light blue links and buttons are not contrasting enough

### ISSUE THREAD

**Issue by rlucke** [opencast/opencast-admin-interface#633]
In idle (#3AA5EF) buttons and links have a contrast ratio of 2.68:1, oh hover it is 2.09:1.

Both are too weak.

**Comment by ziegenberg** [comment]
For reference, the "Edit" button.

On idle: 
![Screenshot from 2024-06-05 21-14-31](https://github.com/opencast/opencast-admin-interface/assets/856916/29307b0c-33c3-425c-bf2f-3ae827cb37ac)

On hover:
![Screenshot from 2024-06-05 21-14-37](https://github.com/opencast/opencast-admin-interface/assets/856916/feb5ddf2-de15-4117-97a0-2faab64e8859)
