### ISSUE TITLE
Translations (partially?) broken

### ISSUE THREAD

**Issue by gregorydlogan** [opencast/opencast-admin-interface#656]
In testing #588, I noticed that translations are not being properly applied.  From my local install:

![image](https://github.com/opencast/opencast-admin-interface/assets/5639561/a8efc1e4-14ed-466c-bdb7-5a6f58a1e894)

and from stable.opencast.org

![image](https://github.com/opencast/opencast-admin-interface/assets/5639561/d5d4b2a1-8a95-45d8-aa4b-a3b82f8ac33f)

Oddly enough, Dutch, and German appear to work correctly in my local install, or at least partially - I have not thoroughly verified that all keys are working, just that the table headers change.

**Comment by gregorydlogan** [comment]
Assigning to @ziegenberg since he's work on this already.  Related to removing the `/app` directory.

**Comment by ziegenberg** [comment]
> Assigning to @ziegenberg since he's work on this already. Related to removing the `/app` directory.

And the renaming of the default branch ... 🤪

**Comment by ziegenberg** [comment]
Most of the lang strings were restored.
