### ISSUE TITLE
Custom roles pattern not respected in ACL tab

### ISSUE THREAD

**Issue by habitant6685** [opencast/opencast-admin-interface#658]
The custom roles pattern seems to not be respected when trying to add roles that are not in the Opencast database (e.g. LDAP users).

Issue seems similar to opencast/opencast#5016.

![Custom Roles Pattern Attempt](https://github.com/opencast/opencast-admin-interface/assets/171841671/5232a55b-a7ef-447d-8c42-3e1a6f3d08f2)

**Comment by lkiesow** [comment]
Maybe instead of this (somewhat weird) ACL pattern you configure in the backend we could just add a button “Add custom role” were you cab just enter any role? I think that will also work better with the new UI proposed in #561.

**Comment by habitant6685** [comment]
I'd agree that adding a more general option to add custom roles might be the more sensible solution moving forward, especially considering that the ACL pattern has often caused bugs in the past.
