### ISSUE TITLE
Click-to-filter-by-presenter does not work anymore

### ISSUE THREAD

**Issue by Rillke** [opencast/opencast-admin-interface#66]
**Describe the bug**
A clear and concise description of what you see:
*Click-to-filter-by-presenter does not work anymore*

**To Reproduce**
1. Go to https://picard.vm2.elan.codes/admin-ui/index.html
2. Log in (admin /opencast)
3. Click on a presenter in the "Presenter(s)" column
4. Nothing happens. In the old Angular.JS Admin UI, a filter was added for the presenter (although not shown, see opencast/opencast#3768  )

Old Angular.js Admin UI:

https://user-images.githubusercontent.com/2311611/178363340-6ac6410a-8344-4119-9c50-e3ce8189b740.mp4

New Picard Admin UI:

https://user-images.githubusercontent.com/2311611/178363297-5e8067d7-e3cd-47a1-9862-358bb472a392.mp4

**Comment by Arnei** [comment]
it seems this has been addressed (although it does properly show, as described in the issue linked in the original post).

https://user-images.githubusercontent.com/14070005/218753645-846ada87-a114-40d0-91bb-53900506ce1d.webm
