### ISSUE TITLE
Click and write in event creation dialog does not work

### ISSUE THREAD

**Issue by Rillke** [opencast/opencast-admin-interface#67]
**Describe the bug**
A clear and concise description of what you see:
*When creating an event in the new Picard Admin UI, click and write does not work as it used to work in the old Angular.JS Admin UI, where you could just click into a blank field and enter the metadata you wanted. In Picard you are forced to click the pencil icon.*

**To Reproduce**
1. Go to https://picard.vm2.elan.codes/admin-ui/index.html#/events/events
2. Click on `+ Event`
3. Enter a title
4. Click into the blank subject field.
5. The title input disappears and the title appears as dotted underlined text but you can't edit the subject

Old Angular.JS Admin UI:

https://user-images.githubusercontent.com/2311611/178361886-8e124a81-97ae-4e25-97fd-6983738ebddd.mp4

New Picard Admin UI:

https://user-images.githubusercontent.com/2311611/178361816-dafcf9c3-e75a-49ac-bd73-97f5ad85ff4f.mp4

**Comment by Arnei** [comment]
This was fixed in #148
