### ISSUE TITLE
Password strength indicator missing

### ISSUE THREAD

**Issue by Rillke** [opencast/opencast-admin-interface#72]
**Describe the bug**
In the old Admin UI when creating a new user, you get a password strength indicator, in the new 

Old (Angular JS):
<img width="822" alt="Screenshot 2022-07-11 at 16 18 50" src="https://user-images.githubusercontent.com/2311611/178285850-7784ae39-a7cc-4b38-8c38-dc204a5ff48c.png">

New (Picard):
<img width="825" alt="Screenshot 2022-07-11 at 16 17 00" src="https://user-images.githubusercontent.com/2311611/178285460-a31e6ad2-c7da-4a75-b61e-ffe5d1239dbc.png">

**To Reproduce**
1. https://picard.vm2.elan.codes/admin-ui/index.html#/users/users
2. Login (admin/opencast)
3. Go to https://picard.vm2.elan.codes/admin-ui/index.html#/users/users
4. Click + Add User

**Comment by ziegenberg** [comment]
See https://github.com/opencast/opencast/pull/3343 for the implementation of the old admin UI.
