### ISSUE TITLE
Sentence goes out of dropdown menu

### ISSUE THREAD

**Issue by mliradelc** [opencast/opencast-admin-interface#74]
**Describe the bug**
When you use a language that has a sentence that is larger than the available space in the dropdown menu, the words go out of the border.

<img width="364" alt="image" src="https://user-images.githubusercontent.com/8040628/178283562-9d998f8e-049b-41a5-a746-9f0aeb390339.png">

**To Reproduce**
1. Select a language that has a large sentence (Example: Spanish)
2. Click on the interrogation symbol

**Environment Information**
 - OS: macOS
 - Browser: Chrome
 - Admin Picard

**Comment by Arnei** [comment]
This seems to have been addressed in the fashion pictured below:

![Image](https://user-images.githubusercontent.com/14070005/218730421-6ceee13c-9315-41c3-9ecd-88f2496bf2d1.png)

**Comment by mliradelc** [comment]
Thanks for closing it, I solved months ago and I forgot closing it.
