### ISSUE TITLE
Endless messages in acl tab when concurrently uploading videos to series

### ISSUE THREAD

**Issue by schuettloeffel-elsa** [opencast/opencast-admin-interface#883]
When concurrently uploading multiple videos to one series, a message is presented in the acl tab. Right now, that message is repeated endlessly, so one cant proceed. 

![image](https://github.com/user-attachments/assets/e7c0279a-4b96-43a9-abf6-3fdecc01418a)

**Comment by mtneug** [comment]
Is this a duplicate of https://github.com/opencast/opencast-admin-interface/issues/829?

**Comment by lkiesow** [comment]
@schuettloeffel-elsa, can you check if the issue still persists in the latest release?

**Comment by schuettloeffel-elsa** [comment]
Yes, works with the lates release.

**Comment by schuettloeffel-elsa** [comment]
(maybe the fix should be backported to the 15.x release?)

**Comment by mtneug** [comment]
For this, the branching structure of this repo needs to be adapted, which hasn't happened yet.

**Comment by schuettloeffel-elsa** [comment]
Ok, then we have to upgrade to OC16 soon
