### ISSUE TITLE
Open Event Details Popup scrolls with page and is displayed at the top of the page (even for event lower down the list)

### ISSUE THREAD

**Issue by marcusm7** [opencast/opencast-admin-interface#919]
Open Event Details Popup scrolls with page and is displayed at the top of the page (even for event lower down the list).
The screenshot shows the Event Details after the Open Event Details Icon of Espresso was clicked.  
  
PC, Linux, Firefox 130.0.1 (64-bit),     Opencast 16.x – b0e0131 – built on 2024-09-29 at stableopencast.org:
![image](https://github.com/user-attachments/assets/6111e409-e773-460f-9936-ef503f43d2bc)  
  
Edit: It also affects other dialogs (i.e. the series dialog and the deletion confirmation dialog).

**Comment by lkiesow** [comment]
It may still make sense to have some scroll functionality since I've seen the dialog become very long in some cases. But maybe we can do that in the dialog and limit the height to `1vh`.
