### ISSUE TITLE
Embedding Code Dialog: the src-URL points to localhost:8080

### ISSUE THREAD

**Issue by marcusm7** [opencast/opencast-admin-interface#949]
The embedding code should point to the real FQDN of the server, but points to localhost:8080.  
(I'm not sure if this is a admin-ui issue or a configuration issue in the backend/ because it's running in a container. Please close if not a bug in the UI.)
![image](https://github.com/user-attachments/assets/4916e5bc-9df5-4ab3-871e-c66c97725603)

**Comment by mtneug** [comment]
IIRC, the domain will be the engage URL or the publication URL with a fallback on the Opencast server URL. In the case of the container images, this is `http://localhost:8080` by default.

**Comment by marcusm7** [comment]
Thanks for the info. It's a configuration issue. Closing this ticket.
